<?php

namespace MyApp\MobileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistancesAttraitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Distances_attraitsRepository extends EntityRepository
{
    
        /**
         * Méthode pour rechercher la liste des distances qui existent pour cet attrait
         */
        public function getRechercheLesDistancesAvecAttrait($idactivite, $idattrait)
        {
            $sql = 'SELECT p FROM MyAppMobileBundle:Distances_attraits p WHERE p.attrait_id = :idattrait AND p.activite_id =:idactivite ';
            $query = $this->getEntityManager()->createQuery($sql);
            $query->setParameter('idattrait', $idattrait);
            $query->setParameter("idactivite", $idactivite);
            return $query->getResult();
        }
        
        /**
         * Retourne les distances pour activités de l'attrait
         */
        public function getListeLesDistancesAttrait($id)
	{
		$sql = 'SELECT p FROM MyAppMobileBundle:Distances_attraits p WHERE p.attrait_id = :id ORDER BY p.activite_id ASC ';
		$query = $this->getEntityManager()->createQuery($sql);
		$query->setParameter('id', $id);
		return $query->getResult();
	}
	
}