<?php

namespace MyApp\MobileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Texte_province_restaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Texte_province_restaurantRepository extends EntityRepository
{
    
    /**
     * Méthode qui valide si on a déjà des textes pour cette province
     */
    public function getValideTexteProvinceExiste($id)
    {
        $sql = 'SELECT p FROM MyAppMobileBundle:Texte_province_restaurant p WHERE p.region =:id';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("id", $id);
        return $query->getResult();
    }
    
    /**
     * Recherche les textes d'accueil
     */
    public function getRechercheTexteAccueil($province, $cuisine)
    {
        $sql = 'SELECT p FROM MyAppMobileBundle:Texte_province_restaurant p WHERE p.province =:province AND p.cuisine =:cuisine';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("province", $province);
        $query->setParameter("cuisine", $cuisine);
        return $query->getResult();
    }
}