<?php

namespace MyApp\GlobalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Texte_province_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Texte_province_categorieRepository extends EntityRepository
{
    
    /**
     * Méthode qui valide si on a déjà des textes pour cette province
     */
    public function getValideTexteProvinceExiste($id)
    {
        $sql = 'SELECT p FROM MyAppGlobalBundle:Texte_province_categorie p WHERE p.province =:id';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("id", $id);
        return $query->getResult();
    }
    
    /**
     * Recherche les textes d'accueil
     */
    public function getRechercheTexteAccueil($province, $cat)
    {
        $sql = 'SELECT p FROM MyAppGlobalBundle:Texte_province_categorie p WHERE p.province =:province AND p.categorie_hebergement =:cat';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("province", $province);
        $query->setParameter("cat", $cat);
        return $query->getResult();
    }
    
    /**
     * Recherche les répertoires
     */
    public function getRechercheRepertoire($cat, $province)
    {
        $sql = 'SELECT p FROM MyAppGlobalBundle:Texte_province_categorie p WHERE p.province =:province AND p.categorie_hebergement IN (:cat)';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("province", $province);
        $query->setParameter("cat", $cat);
        return $query->getResult();
    }
}