<?php

namespace MyApp\GlobalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Texte_province_activite_corporativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Texte_province_activite_corporativeRepository extends EntityRepository
{
    
    
    /**
     * Recherche les textes d'accueil
     */
    public function getRechercheTexteAccueil($province)
    {
        $sql = 'SELECT p FROM MyAppGlobalBundle:Texte_province_activite_corporative p WHERE p.province =:province';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("province", $province);
        return $query->getResult();
    }
}