<?php

namespace MyApp\GlobalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Texte_region_santeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Texte_region_santeRepository extends EntityRepository
{
    
    /**
     * Méthode qui valide si on a déjà des textes pour cette région
     */
    public function getValideTexteRegionExiste($id)
    {
        $sql = 'SELECT p FROM MyAppGlobalBundle:Texte_region_sante p WHERE p.region =:id';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("id", $id);
        return $query->getResult();
    }
    
    /**
     * Recherche les textes d'accueil
     */
    public function getRechercheTexteAccueil($region, $sante)
    {
        $sql = 'SELECT p FROM MyAppGlobalBundle:Texte_region_sante p WHERE p.region =:region AND p.sante =:soin';
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter("region", $region);
        $query->setParameter("soin", $sante);
        return $query->getResult();
    }
}