parameters:
#    my_app_global.example.class: MyApp\GlobalBundle\Example

services:
#    my_app_global.example:
#        class: %my_app_global.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
